2024-04-30 19:43:08,142 - database_error_logger - ERROR - Failed to update one document in 'hangman_games': localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66311f7e0e747ea9ef6bc8cf, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
Traceback (most recent call last):
  File "Z:\CodeAcademy\hangman_game\hangman_app\models\mongo_functions.py", line 104, in update_one_document
    result = collection.update_one(query, {"$set": update})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\collection.py", line 1086, in update_one
    self._update_retryable(
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\collection.py", line 881, in _update_retryable
    return self.__database.client._retryable_write(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1522, in _retryable_write
    with self._tmp_session(session) as s:
  File "Z:\Python\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1840, in _tmp_session
    s = self._ensure_session(session)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1823, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1766, in __start_session
    self._topology._check_implicit_session_support()
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\topology.py", line 573, in _check_implicit_session_support
    self._check_session_support()
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\topology.py", line 589, in _check_session_support
    self._select_servers_loop(
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\topology.py", line 259, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66311f7e0e747ea9ef6bc8cf, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-04-30 19:43:38,218 - database_error_logger - ERROR - Failed to update one document in 'hangman_games': localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66311f7e0e747ea9ef6bc8cf, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
Traceback (most recent call last):
  File "Z:\CodeAcademy\hangman_game\hangman_app\models\mongo_functions.py", line 104, in update_one_document
    result = collection.update_one(query, {"$set": update})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\collection.py", line 1086, in update_one
    self._update_retryable(
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\collection.py", line 881, in _update_retryable
    return self.__database.client._retryable_write(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1522, in _retryable_write
    with self._tmp_session(session) as s:
  File "Z:\Python\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1840, in _tmp_session
    s = self._ensure_session(session)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1823, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1766, in __start_session
    self._topology._check_implicit_session_support()
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\topology.py", line 573, in _check_implicit_session_support
    self._check_session_support()
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\topology.py", line 589, in _check_session_support
    self._select_servers_loop(
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\topology.py", line 259, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66311f7e0e747ea9ef6bc8cf, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-04-30 19:44:08,316 - database_error_logger - ERROR - Failed to update one document in 'hangman_games': localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66311f7e0e747ea9ef6bc8cf, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
Traceback (most recent call last):
  File "Z:\CodeAcademy\hangman_game\hangman_app\models\mongo_functions.py", line 104, in update_one_document
    result = collection.update_one(query, {"$set": update})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\collection.py", line 1086, in update_one
    self._update_retryable(
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\collection.py", line 881, in _update_retryable
    return self.__database.client._retryable_write(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1522, in _retryable_write
    with self._tmp_session(session) as s:
  File "Z:\Python\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1840, in _tmp_session
    s = self._ensure_session(session)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1823, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1766, in __start_session
    self._topology._check_implicit_session_support()
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\topology.py", line 573, in _check_implicit_session_support
    self._check_session_support()
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\topology.py", line 589, in _check_session_support
    self._select_servers_loop(
  File "Z:\CodeAcademy\hangman_game\.venv\Lib\site-packages\pymongo\topology.py", line 259, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66311f7e0e747ea9ef6bc8cf, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
